// Snake type definitions for Snake Battle Royale
// Each type has a unique cyberpunk aesthetic

export const SNAKE_TYPES = {
  NEON_GREEN: {
    id: 'NEON_GREEN',
    name: 'Neon Green',
    label: '🟢 Neon Green',
    description: 'The classic serpent reborn in neon. Fast and deadly.',
    bodyColor: '#00ff41',
    headColor: '#00ff41',
    glowColor: '#00ff41',
    glowIntensity: 20,
    tailColor: '#005514',
    shadowColor: 'rgba(0, 255, 65, 0.6)',
    accentColor: '#39ff14',
    style: 'classic',
  },
  CYBER_BLUE: {
    id: 'CYBER_BLUE',
    name: 'Cyber Blue',
    label: '🔵 Cyber Blue',
    description: 'A data-stream entity from the net. Leaves ice in its wake.',
    bodyColor: '#00d4ff',
    headColor: '#00d4ff',
    glowColor: '#00d4ff',
    glowIntensity: 25,
    tailColor: '#003344',
    shadowColor: 'rgba(0, 212, 255, 0.7)',
    accentColor: '#0affef',
    style: 'glowing',
  },
  HOT_PINK: {
    id: 'HOT_PINK',
    name: 'Hot Pink',
    label: '🩷 Hot Pink',
    description: 'Vibrant. Chaotic. Unstoppable. Leaves a trail of magenta fire.',
    bodyColor: '#ff007f',
    headColor: '#ff007f',
    glowColor: '#ff007f',
    glowIntensity: 22,
    tailColor: '#4a0020',
    shadowColor: 'rgba(255, 0, 127, 0.65)',
    accentColor: '#ff69b4',
    style: 'vibrant',
  },
  ELECTRIC_ORANGE: {
    id: 'ELECTRIC_ORANGE',
    name: 'Electric Orange',
    label: '🟠 Electric Orange',
    description: 'Crackling with raw energy. Burns everything it touches.',
    bodyColor: '#ff6600',
    headColor: '#ffaa00',
    glowColor: '#ff6600',
    glowIntensity: 24,
    tailColor: '#3d1800',
    shadowColor: 'rgba(255, 102, 0, 0.7)',
    accentColor: '#ffd700',
    style: 'energy',
  },
  VOID_PURPLE: {
    id: 'VOID_PURPLE',
    name: 'Void Purple',
    label: '🟣 Void Purple',
    description: 'A shadow from the abyss. Absorbs light. Absorbs everything.',
    bodyColor: '#9d00ff',
    headColor: '#bf40ff',
    glowColor: '#9d00ff',
    glowIntensity: 18,
    tailColor: '#1a0033',
    shadowColor: 'rgba(157, 0, 255, 0.5)',
    accentColor: '#cc66ff',
    style: 'dark',
  },
};

export const SNAKE_TYPE_IDS = Object.keys(SNAKE_TYPES);

export const DEFAULT_SNAKE_TYPE = 'NEON_GREEN';
